### ISSUE TITLE
`getPayloadClient()` fails in server actions

### ISSUE THREAD

**Issue by Endy3032** [payloadcms/next-payload#91] opened 2023-11-14 17:19 UTC
When test building and serving my app with `next build` and `next start`, I get this error whenever my app imports a server action ("use server") with `getPayloadClient()` called. This problem isnt present when running in `next dev` tho

```
⨯ /workspaces/Scholendo/.next/server/app/(user)/auth/page.js:18089
((s = JSON.parse(JSON.stringify(s = yield o.findOneAndUpdate({
^^^^^

SyntaxError: Unexpected strict mode reserved word
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1153:20)
at Module._compile (node:internal/modules/cjs/loader:1205:27)
at Module._compile (/workspaces/Scholendo/node_modules/pirates/lib/index.js:117:24)
at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
at Object.newLoader [as .js] (/workspaces/Scholendo/node_modules/pirates/lib/index.js:121:7)
at Module.load (node:internal/modules/cjs/loader:1091:32)
at Module._load (node:internal/modules/cjs/loader:938:12)
at Module.require (node:internal/modules/cjs/loader:1115:19)
at mod.require (/workspaces/Scholendo/node_modules/next/dist/server/require-hook.js:64:28)
```

**Comment by Endy3032** [comment] 2023-11-19 11:04
seems like this doesnt happen on vercel with next@13 and local `next dev`, still happens in a local build tho

**Comment by jacobsfletch** [comment] 2024-04-12 14:08
Hey @Endy3032, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the 3.x-beta label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:08 UTC
