### ISSUE TITLE
Can't login '/admin' after creating initial admin account on '/admin' page (Next.JS 14 with next-payload)

### ISSUE THREAD

**Issue by kuskhan** [payloadcms/next-payload#95] opened 2023-11-19 04:02 UTC
It redirects to the main admin page after creating the initial admin account when I use PayloadCMS as a standalone service from Next.js. However, it constantly redirects to the admin login page after failing to log in automatically following the creation of an initial admin account.
If I downgrade to Next.js 13, it works. In both case, they show a weird warning on the devloper console that does not appear in the standalone case.

The error messages in the console window are like this.
- app-index.js:32 Warning: ToastContainer: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code.
<img width="1410" alt="Screenshot 2023-11-19 at 12 49 15" src="https://github.com/payloadcms/next-payload/assets/13177330/a28c78dc-d976-499f-8e48-5379cb5b4598">

**Comment by mikeploythai** [comment] 2023-11-28 10:37
Just wanted to +1 on this, had to downgrade to next@13 for my login to proceed.

**Comment by jacobsfletch** [comment] 2024-04-12 14:06
Hey @kuskhan, @mikeploythai, @andersmattson, and @maxjunerd, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:06 UTC
