### ISSUE TITLE
Custom endpoints

### ISSUE THREAD

**Issue by Shmookoff** [payloadcms/next-payload#73] opened 2023-09-20 09:32 UTC
Any information on how to do custom endpoints with next-payload?
Just configuring a custom endpoint:
```typescript
{
  path: "/file/:filename",
  method: "get",
  handler: (req, res, next) => {
    res.status(200).json({ filename: req.params.filename });
  },
}
```
doesn't seem to work.

**Comment by 60pfennig** [comment] 2023-09-27 13:38
I have the same problem. I guess for now you have to write you own endpoints in the pages/api folder.

**Comment by Trugamr** [comment] 2023-10-28 05:49
Looks like Payload now relies on Next API routes to pass requests, you can use [API Routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes) or [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers),

**Comment by jacobsfletch** [comment] 2024-04-12 14:14
Hey there @Shmookoff, @60pfennig, and @Trugamr, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:14 UTC
