### ISSUE TITLE
Status 500 error with vercel deploy (next14)

### ISSUE THREAD

**Issue by silveltman** [payloadcms/next-payload#93] opened 2023-11-17 16:35 UTC
I just tried this setup and connected a mongoDB using vercel's mongoDB integration.
When navigating to the admin panel I get a status 500 error in the browser console.

This is one of the vercel error logs:
```
modules/payload/dist/collections/operations/create.js
- /var/task/node_modules/payload/dist/collections/operations/local/create.js
- /var/task/node_modules/payload/dist/collections/operations/local/index.js
- /var/task/node_modules/payload/dist/payload.js
- /var/task/.next/server/pages/api/[collection]/me.js
- /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25599
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at r.<computed>.e._load (/var/task/___vc/__launcher/__launcher.js:14:2516)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at w.require (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25815)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/task/node_modules/payload/dist/uploads/generateFileData.js:16:55)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/payload/dist/uploads/generateFileData.js',
    '/var/task/node_modules/payload/dist/collections/operations/create.js',
    '/var/task/node_modules/payload/dist/collections/operations/local/create.js',
    '/var/task/node_modules/payload/dist/collections/operations/local/index.js',
    '/var/task/node_modules/payload/dist/payload.js',
    '/var/task/.next/server/pages/api/[collection]/me.js',
    '/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js',
    '/var/task/___next_launcher.cjs'
  ]
}
Error: Cannot find module 'sharp'
Require stack:
- /var/task/node_modules/payload/dist/uploads/generateFileData.js
- /var/task/node_modules/payload/dist/collections/operations/create.js
- /var/task/node_modules/payload/dist/collections/operations/local/create.js
- /var/task/node_modules/payload/dist/collections/operations/local/index.js
- /var/task/node_modules/payload/dist/payload.js
- /var/task/.next/server/pages/api/[collection]/me.js
- /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25599
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at r.<computed>.e._load (/var/task/___vc/__launcher/__launcher.js:14:2516)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at w.require (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25815)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/task/node_modules/payload/dist/uploads/generateFileData.js:16:55)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/payload/dist/uploads/generateFileData.js',
    '/var/task/node_modules/payload/dist/collections/operations/create.js',
    '/var/task/node_modules/payload/dist/collections/operations/local/create.js',
    '/var/task/node_modules/payload/dist/collections/operations/local/index.js',
    '/var/task/node_modules/payload/dist/payload.js',
    '/var/task/.next/server/pages/api/[collection]/me.js',
    '/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js',
    '/var/task/___next_launcher.cjs'
  ]
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError

```

**Comment by silveltman** [comment] 2023-11-18 13:53
Fixed with `yarn add next@13`

**Comment by jacobsfletch** [comment] 2024-04-12 14:07
Hi again @silveltman , this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the 3.x-beta label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:07 UTC
