### ISSUE TITLE
Payload 2.0 Bundler Issues

### ISSUE THREAD

**Issue by ghardin1314** [payloadcms/next-payload#80] opened 2023-10-17 20:12 UTC
Running into issues trying to use the latest versions of payload and this repo when trying to access the admin dashboard. When trying to use the vite bundler I get this error:

```
 ⨯ ./node_modules/.pnpm/@rollup+plugin-image@3.0.3/node_modules/@rollup/plugin-image/dist/cjs/index.js:5:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/@payloadcms+bundler-vite@0.1.2_@types+node@20.8.6_react-dom@18.2.0/node_modules/@payloadcms/bundler-vite/dist/config.js
./node_modules/.pnpm/@payloadcms+bundler-vite@0.1.2_@types+node@20.8.6_react-dom@18.2.0/node_modules/@payloadcms/bundler-vite/dist/scripts/build.js
./node_modules/.pnpm/@payloadcms+bundler-vite@0.1.2_@types+node@20.8.6_react-dom@18.2.0/node_modules/@payloadcms/bundler-vite/dist/index.js
./src/payload/payload.config.ts
./node_modules/.pnpm/payload@2.0.9_@types+react@18.2.28_typescript@5.2.2_webpack@5.89.0/node_modules/payload/dist/admin/Root.js
./src/app/(payload)/admin/page.tsx
```

When trying to use the default webpack bunder, I get this error:

```
 ⨯ uncaughtException: Error: Cannot find module '/home/ghard1314/Documents/github/experiments/next-payload/.next/server/vendor-chunks/lib/worker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:201:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: the worker thread exited
    at Worker.onWorkerExit (webpack-internal:///(api)/./node_modules/.pnpm/thread-stream@2.4.1/node_modules/thread-stream/index.js:201:32)
    at Worker.emit (node:events:513:28)
    at [kOnExit] (node:internal/worker:279:10)
    at Worker.<computed>.onexit (node:internal/worker:199:20)
    at Worker.callbackTrampoline (node:internal/async_hooks:130:17)
 ⨯ node_modules/.pnpm/thread-stream@2.4.1/node_modules/thread-stream/index.js (201:0) @ Worker.onWorkerExit
 ⨯ uncaughtException: Error: the worker thread exited
    at Worker.onWorkerExit (webpack-internal:///(api)/./node_modules/.pnpm/thread-stream@2.4.1/node_modules/thread-stream/index.js:201:32)
    at Worker.emit (node:events:513:28)
    at [kOnExit] (node:internal/worker:279:10)
    at Worker.<computed>.onexit (node:internal/worker:199:20)
    at Worker.callbackTrampoline (node:internal/async_hooks:130:17)
null
```

Minimal example here: https://github.com/ghardin1314/payload-next

**Comment by ghardin1314** [comment] 2023-10-17 21:36
Per discord convo, cant use vite bundler as Nextjs handles all the bundling

Turns out my app was silently crashing due to bad database credentials. That error did not show up anywhere on the console or in the network requests.

As for the worker thread error, that seems to be related to Pino. Updated error logs:

```
 ⨯ uncaughtException: Error: the worker has exited
    at ThreadStream.write (webpack-internal:///(api)/../../node_modules/.pnpm/thread-stream@2.4.1/node_modules/thread-stream/index.js:235:19)
    at Pino.write (webpack-internal:///(api)/../../node_modules/.pnpm/pino@8.15.0/node_modules/pino/lib/proto.js:217:10)
    at Pino.LOG [as info] (webpack-internal:///(api)/../../node_modules/.pnpm/pino@8.15.0/node_modules/pino/lib/tools.js:71:21)
    at Object.connect (/home/ghard1314/Documents/github/experiments/mstr-v2/node_modules/.pnpm/@payloadcms+db-mongodb@1.0.3/node_modules/@payloadcms/db-mongodb/dist/connect.js:56:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BasePayload.init (webpack-internal:///(api)/../../node_modules/.pnpm/payload@2.0.7_@types+react@18.2.24_typescript@5.2.2_webpack@5.89.0/node_modules/payload/dist/payload.js:84:13)
    at async getPayload (webpack-internal:///(api)/../../node_modules/.pnpm/payload@2.0.7_@types+react@18.2.24_typescript@5.2.2_webpack@5.89.0/node_modules/payload/dist/payload.js:244:26)
null
```

I think this might be related to https://github.com/vercel/next.js/issues/54289#issuecomment-1686401300

**Comment by ghardin1314** [comment] 2023-10-19 18:32
Seems like this might be related to running in a monorepo setup

https://github.com/vercel/next.js/discussions/46987#discussioncomment-7331093

**Comment by IAmNatch** [comment] 2024-01-19 22:59
Did you end up resolving the `fs` issue? Mine seems to be related to using `dotenv` inside the file, which is not available on the browser. Previously the browser would not access this portion of the config.

**Comment by IAmNatch** [comment] 2024-01-19 23:51
I resolved my FS issues by following this: https://payloadcms.com/community-help/discord/cannot-resolve-fs 

Essentially creating a empty module that gets used by webpack. 

I'm now hitting Pino Issues as well: `unable to determine transport target for "pino-pretty`

**Comment by IAmNatch** [comment] 2024-01-20 00:53
For now I'll solved the pino issue by replacing the transport as such:
```
loggerDestination: pino.destination(),
```

This works for now, though I'd love to use the default implementation in the future. I'm sure it will be solved when this repo is deprecated, but I'll leave my solution in case it would beenfit anyone.

**Comment by sandbox4013** [comment] 2024-02-29 18:07
> For now I'll solved the pino issue by replacing the transport as such:
> 
> ```
> loggerDestination: pino.destination(),
> ```
> 
> This works for now, though I'd love to use the default implementation in the future. I'm sure it will be solved when this repo is deprecated, but I'll leave my solution in case it would benefit anyone.

Doesn't work unfortunately
<img width="701" alt="image" src="https://github.com/payloadcms/next-payload/assets/49528851/81a8c647-6e0d-4caa-8b23-3f707af43180">

**Comment by jacobsfletch** [comment] 2024-04-12 14:12
Hey there @ghardin1314, @IAmNatch, and @sandbox4013, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:12 UTC
