### ISSUE TITLE
API Key: You are not allowed to perform this action.

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/next-payload#87] opened 2023-11-01 21:35 UTC
I cannot access the api routes from a server (both local host). It neither works if I have 2 different servers (one Next Project for the website and one for Payload) nor If it's the same server (payload in the same next.js project as the website). The error message from Payload is:
```
ERROR (payload): Forbidden: You are not allowed to perform this action.
at executeAccess (webpack-internal:///(api)/./node_modules/payload/dist/auth/executeAccess.js:16:49)
at async findOne (webpack-internal:///(api)/./node_modules/payload/dist/globals/operations/findOne.js:31:28)
at async handler (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/handlers/globals/[global]/index.js:37:36)
```

I'm using Payload 2 & Next 14

It does work via Cookie/Token: `'Cookie': 'payload-token=${loginData.token}'`. `loginData` is obtained via the /login endpoint.
On a side note: This "payload-token" is not mentioned anywhere in the documentation.

**Comment by jacobsfletch** [comment] 2024-04-12 14:08
Hey @johannesschaffer, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the 3.x-beta label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:08 UTC
