### ISSUE TITLE
Monorepo example/template

### ISSUE THREAD

**Issue by arielvieira** [payloadcms/next-payload#79] opened 2023-10-16 04:28 UTC
Is `@payloadcms/next-payload` compatible within a `monorepo` setup?

If so can you guys provide a example/tempate for usage within a monorepo where the `payload` folder for config and client live in a separated package? 

I tried to setup a monorepo with next-payload but when trying to specify a `configPath` for a package outside the next.js app 
```ts
module.exports = withPayload(nextConfig, {
  // path outside next.js app package
  configPath: path.resolve(__dirname, "..", "..", "packages/payload/payload.config"),
})
```

It crashes with `SyntaxError: Cannot use import statement outside a module`
```
λ yarn dev
yarn run v1.22.19
$ next dev
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
..\next-payload-demo\packages\payload\payload.config.ts:2
import path from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .ts] (..\next-payload-demo\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at loadPayloadConfig (..\next-payload-demo\node_modules\@payloadcms\next-payload\loadPayloadConfig.js:38:25) {
  type: 'SyntaxError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried transpiling the package with nextjs `transpilePackages` but it also didn't work.

**Comment by ghardin1314** [comment] 2023-10-17 23:27
Tried something very similar, except just importing `collections` from a package into my payload config which is inside my app folder. It seems like `payload.config.ts` gets evaluated before transpilePackages runs. 

It works if I start my app in dev mode and then hot reload by updating my config. So that leads me to believe its only an issue of order of operations or something

**Comment by willviles** [comment] 2023-10-20 08:23
This is where referencing a `payload.config.ts` via a path is an unworkable solution.

I have previously suggested in https://github.com/payloadcms/payload/discussions/2417#discussioncomment-6186599 that Payload would benefit from generating a `payload-client` package, which exposes a connection handler and all generated types to make utilising the Local API outside of a Payload project much simpler.

**Comment by silveltman** [comment] 2023-11-22 14:37
Running into the same problem here.

**Comment by jacobsfletch** [comment] 2024-04-12 14:13
Hey there @arielvieira, @willviles, and @silveltman, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:13 UTC
