### ISSUE TITLE
Custom views don't work

### ISSUE THREAD

**Issue by ccapndave** [payloadcms/next-payload#89] opened 2023-11-08 10:21 UTC
(Full disclosure - I'm not 100% sure that this is a `next-payload` issue rather than just a Payload issue, but I think it probably is...)

I'd like to use a custom view as documented at https://payloadcms.com/docs/admin/components#building-a-custom-view-component.

I've added this to my Payload config:

```
 admin: {
    components: {
      views: {
        CrowdinView: {
          Component: CrowdinComponent,
          path: "/crowdin"
        }
      }
    }
  },
```

Using this component:

```
import { AdminViewComponent } from "payload/config";

const CrowdinComponent: AdminViewComponent = () => {
  return <div>Hello</div>;
};

export { CrowdinServerComponent };
```

This works as expected.

However, if I make the component a client component by adding `"use client"` to the top of the custom view, the NextJS site explodes with this error:

```
⨯ TypeError: Cannot convert a Symbol value to a string
    at Proxy.toString (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at eval (./payload/payload.config.ts:31:125)
    at (rsc)/./payload/payload.config.ts (/Users/dave/Projects/mysite/.next/server/app/(site)/[locale]/(home)/page.js:878:13)
    at __webpack_require__ (/Users/dave/Projects/mysite/.next/server/webpack-runtime.js:30:52)
    at eval (./payload/payloadClient.ts:8:73)
    at (rsc)/./payload/payloadClient.ts (/Users/dave/Projects/mysite/.next/server/app/(site)/[locale]/(home)/page.js:884:13)
    at __webpack_require__ (/Users/dave/Projects/mysite/.next/server/webpack-runtime.js:30:52)
    at eval ([locale]/layout.tsx:13:80)
    at (rsc)/./app/(site)/[locale]/layout.tsx (/Users/dave/Projects/mysite/.next/server/app/(site)/[locale]/(home)/page.js:542:13)
    at Function.__webpack_require__ (/Users/dave/Projects/mysite/.next/server/webpack-runtime.js:30:52)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

the Payload admin explodes with this error:

```
 ⨯ TypeError: getPayload is not a function
    at eval (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:9:29)
    at /Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
```

and `yarn build` explodes with this error:

```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at parse (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/micromatch/index.js:15:9078)
    at picomatch.makeRe (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
    at picomatch (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
    at /Users/dave/Projects/mysite/node_modules/next/dist/compiled/micromatch/index.js:15:19294
    at Array.map (<anonymous>)
    at picomatch (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
    at micromatch.isMatch (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
    at /Users/dave/Projects/mysite/node_modules/next/dist/build/collect-build-traces.js:244:48
    at shouldIgnore (/Users/dave/Projects/mysite/node_modules/next/dist/build/collect-build-traces.js:75:9)
```

Since I need client components in my view for it to be useful, I then tried to keep the custom view as a server component, but import a client component:

```
import { AdminViewComponent } from "payload/config";
import { useConfig } from "payload/dist/admin/components/utilities/Config";
import { CrowdinComponent } from "./crowdin/CrowdinComponent";

const CrowdinServerComponent: AdminViewComponent = () => {
  const config = useConfig();

  return <CrowdinComponent config={config} />;
};

export { CrowdinServerComponent };
```

```
"use client"

type Props = {
  config: SanitizedConfig;
};

export function CrowdinComponent({ config }: Props) {
  ...
}
```

In this case, the NextJS site loads successfully, but the Payload admin fails with this error.

```
 ⨯ node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js (8:24) @ getPayload
 ⨯ TypeError: getPayload is not a function
    at eval (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:9:29)
    at /Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:131:36
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:103
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:28)
    at K (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2970)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async U.render (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3827)
    at async DevServer.runApi (/Users/dave/Projects/mysite/node_modules/next/dist/server/next-server.js:548:9) {
  page: '/api/[collection]/init'
}
null
 ⨯ node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js (8:24) @ getPayload
 ⨯ TypeError: getPayload is not a function
    at eval (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:9:29)
    at /Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:131:36
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:103
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:28)
    at K (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2970)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async U.render (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3827)
    at async DevServer.runApi (/Users/dave/Projects/mysite/node_modules/next/dist/server/next-server.js:548:9) {
  page: '/api/[collection]/me'
}
null
 ⨯ node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js (8:24) @ getPayload
 ⨯ TypeError: getPayload is not a function
    at eval (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:9:29)
    at /Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:131:36
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:103
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:28)
    at K (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2970)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async U.render (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3827)
    at async DevServer.runApi (/Users/dave/Projects/mysite/node_modules/next/dist/server/next-server.js:548:9) {
  page: '/api/[collection]/init'
}
null
 ⨯ node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js (8:24) @ getPayload
 ⨯ TypeError: getPayload is not a function
    at eval (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:9:29)
    at /Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:131:36
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:103
    at NoopContextManager.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/Users/dave/Projects/mysite/node_modules/next/dist/server/lib/trace/tracer.js:120:28)
    at K (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2970)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async U.render (/Users/dave/Projects/mysite/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3827)
    at async DevServer.runApi (/Users/dave/Projects/mysite/node_modules/next/dist/server/next-server.js:548:9) {
  page: '/api/[collection]/me'
}
null
```

Any advice gratefully received!

**Comment by ccapndave** [comment] 2023-11-09 07:57
Another developer on Discord has verified that this works for them without `next-payload`, so it definitely seems to be something to do with that.

**Comment by jacobsfletch** [comment] 2024-04-12 14:08
Hey @ccapndave, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the 3.x-beta label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:08 UTC
