### ISSUE TITLE
Working with cloud storage private buckets

### ISSUE THREAD

**Issue by quangbuule** [payloadcms/next-payload#68] opened 2023-09-07 08:25 UTC
Hi guys, after several tries, I managed to use Google Cloud Storage for uploads. However, the objects are required to be public in order for this to work.

Is there any way that we can use the cloud storages without `disablePayloadAccessControl: true` within Next.js? 

Thanks

**Comment by IAmNatch** [comment] 2023-09-11 22:17
This is likely more of a question for [payloadcms/plugin-cloud-storage](https://github.com/payloadcms/plugin-cloud-storage), but you should be able to set `acl: "Public"` on the google cloud storage plugin, while keeping `disablePayloadAccessControl` set to `false`. 

This should result in the ACL being public when directly linking to the files, while access being restricted based on payload's rules when trying to access the files via any of the payload APIs. 

If you want to access the files with public access through payload, you will need to set the `disablePayloadAccessControl` to `true`. 

If you're still running into issues, feel free to describe more of your use case and I'll do my best to answer!

**Comment by jacobsfletch** [comment] 2024-04-12 14:16
Hey there @quangbuule and @IAmNatch, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:16 UTC
