### ISSUE TITLE
Memory leak on page reload

### ISSUE THREAD

**Issue by Arctomachine** [payloadcms/next-payload#32] opened 2023-05-20 01:04 UTC
Dev mode:
During loading of admin panel multiple errors are listed in console. Server takes lots of memory.
After page refresh all errors are listed again and memory consumption keeps increasing

Build mode:
Fewer errors, but build builds successfully

Start mode:
Infinite loading screen. Another error is given in console instead: `TypeError: Cannot convert undefined or null to object` that points to somewhere in chunks.

All errors are similar, just module name differs
```
./node_modules/.pnpm/mongodb@4.8.1/node_modules/mongodb/lib/utils.js
Module not found: Can't resolve 'mongodb-client-encryption' in 'path-to-current-project\node_modules\.pnpm\mongodb@4.8.1\node_modules\mongodb\lib'

Import trace for requested module:
./node_modules/.pnpm/mongodb@4.8.1/node_modules/mongodb/lib/utils.js
./node_modules/.pnpm/mongodb@4.8.1/node_modules/mongodb/lib/collection.js
./node_modules/.pnpm/mongodb@4.8.1/node_modules/mongodb/lib/index.js
./node_modules/.pnpm/mongoose@6.5.0/node_modules/mongoose/lib/index.js
./node_modules/.pnpm/mongoose@6.5.0/node_modules/mongoose/index.js
./node_modules/.pnpm/payload@1.8.2_monaco-editor@0.38.0_scheduler@0.23.0_typescript@5.0.4/node_modules/payload/dist/payload.js
./payload/payloadClient.ts
./node_modules/.pnpm/@payloadcms+next-payload@0.0.23_payload@1.8.2_webpack@4.46.0/node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js
./node_modules/.pnpm/@payloadcms+next-payload@0.0.23_payload@1.8.2_webpack@4.46.0/node_modules/@payloadcms/next-payload/dist/handlers/[collection]/init.js
```

**Comment by Arctomachine** [comment] 2023-05-20 18:05
Looks like it happens because of pnpm. With yarn everything works without errors and memory leaks.

**Comment by ahaasler** [comment] 2023-06-05 06:02
This is a duplicate of #24, which contains a workaround for pnpm.

**Closed** 2023-06-07 09:17 UTC
