### ISSUE TITLE
Can't resolve '@payloadcms/next-payload/getPayload'

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/next-payload#6] opened 2023-04-06 23:57 UTC
@payloadcms/next-payload/middleware/withPayload.js imports `@payloadcms/next-payload/getPayload` which doesn't exist

**Comment by jmikrut** [comment] 2023-04-10 19:37
Hey @johannesschaffer — this is actually handled by a Webpack alias which should point to a file that does indeed exist, but I assume this is giving you a TS error. We will add some safety to this so it doesn't throw an error.

**Comment by johannesschaffer** [comment] 2023-04-10 19:54
I'm not 100% sure, since I don't have the project currently at hand, but I'm fairly certain it was a runtime error (it occurred in dev mode. I'm pretty sure TS errors don't show up there)

**Comment by JarrodMFlesch** [comment] 2023-04-18 20:34
@johannesschaffer this should be fixed with the latest version. Take a look at the updated readme, let me know if you have any questions!

**Comment by kanian** [comment] 2023-06-23 22:09
Hi I am having the same issue. Doesn't happen locally. Only when deploying to vercel.

**Comment by otomir23** [comment] 2023-08-20 15:13
I have the same issue on dev environment. 
```
./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:1:19
Module not found: Can't resolve '@payloadcms/next-payload/getPayload'
```

I have the following config:
```js
const path = require("path");
const { withPayload } = require("@payloadcms/next-payload");
const withNextIntl = require('next-intl/plugin')();

module.exports = withPayload(
    withNextIntl({
        webpack: (config) => {
            config.module.rules.push({
                test: /\.md$/,
                use: 'raw-loader',
            });
            return config;
        },
        images: {
            remotePatterns: [
                {
                    protocol: 'https',
                    hostname: 'avatars.githubusercontent.com',
                },
            ],
            dangerouslyAllowSVG: true
        }
    }),
    {
        configPath: path.resolve(__dirname, "./src/payload/payload.config.ts"),
    }
);
```

**Comment by edwardbc** [comment] 2023-08-29 23:52
I'm having the exact same issue with latest version and following all the steps from the README and accesing /admin

```
./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:1:19
Module not found: Can't resolve '@payloadcms/next-payload/getPayload'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@payloadcms/next-payload/dist/handlers/[collection]/init.js
./src/pages/api/[collection]/init.ts
```

**Comment by lucianogreiner** [comment] 2023-08-30 22:21
Same here

**Comment by otomir23** [comment] 2023-08-31 09:38
@JarrodMFlesch can you reopen the issue? Or should I create a new one?

**Comment by JarrodMFlesch** [comment] 2023-08-31 11:06
I reopened the issue and will check it out when I can, I'll be offline until Tuesday. But I will check it out! 🙂

**Comment by JarrodMFlesch** [comment] 2023-08-31 15:59
I just released a new version, `0.0.37`. I do not think it will affect your environment issues though. Still recommend installing it.

@otomir23 @lucianogreiner @edwardbc @kanian, can you tell me what version of Next you are using? I am unable to reproduce this issue. I ran `yarn add next@latest` and was unable to reproduce the issue. 

Also, when working locally, try removing the `.next` folder before spinning up your dev server. If you are still experiencing the issue, please try to recreate it within the [next-payload-demo](https://github.com/payloadcms/next-payload-demo) repo, that is what I have been using to test and it has been working fine both locally and deployed to vercel 👍

**Closed by JarrodMFlesch** 2023-08-31 15:59 UTC

**Comment by otomir23** [comment] 2023-08-31 20:04
Updated `next`, `payload` and `next-payload` to latest and removed `.next`, no luck. I will try to reproduce within `next-payload-demo` a bit later.

**Comment by edwardbc** [comment] 2023-09-01 04:46
@JarrodMFlesch 
"next": "^13.4.7",
"payload": "^1.15.2",

Note, I didn't use the "demo" but an existing Next app of mine, which had a default folder structure of "src/app" instead of the structure of the next-payload-demo that lacks the "src" folder

I solved the issue by just moving the /payload/ folder to root instead of it being inside src/ next to app as it was automatically installed

**Comment by JarrodMFlesch** [comment] 2023-09-01 10:55
> @JarrodMFlesch 
> 
> "next": "^13.4.7",
> 
> "payload": "^1.15.2",
> 
> 
> 
> Note, I didn't use the "demo" but an existing Next app of mine, which had a default folder structure of "src/app" instead of the structure of the next-payload-demo that lacks the "src" folder
> 
> 
> 
> I solved the issue by just moving the /payload/ folder to root instead of it being inside src/ next to app as it was automatically installed 

@edwardbc I think you just needed to set the payloadPath and possibly the configPath in the withPayload plugin options with your next config file. The readme talks about those paths a little bit, let me know if it makes sense!

**Comment by seripap** [comment] 2023-11-02 15:29
I am running into this with `"@payloadcms/next-payload": "^0.1.9"`

**Comment by alimoli** [comment] 2023-12-05 08:29
Thank you for the answer @JarrodMFlesch !
I checked it closer and I saw that the issue was the missing `PAYLOAD_CONFIG_PATH=payload/payload.config.ts` env.
All good then, but can I ask you the reason/usage of this environment variable?
Thank you for your support. 🙏

**Comment by JarrodMFlesch** [comment] 2023-12-05 14:18
@alimoli that is used internally by Payload for functionality, required by Payload itself which this package relies on.
