### ISSUE TITLE
Full restart required for changes to apply correctly

### ISSUE THREAD

**Issue by silveltman** [payloadcms/next-payload#99] opened 2023-11-25 20:19 UTC
When changing a field for example, a reload of the page does show the change. However, the functionality does not update, meaning:

- Changes in hooks don't work
- Newly create fields cannot actually be used, they only appear to be visual

Restarting the dev server fixes the problem, but this literally takes like 30 seconds

**Comment by silveltman** [comment] 2023-11-27 12:26
Somewhat related to https://github.com/payloadcms/next-payload/issues/26 . However, I think there is a difference between HMR not working (which should be quick and instant) vs updates not working al all and requiring a full dev server restart

**Comment by jacobsfletch** [comment] 2024-04-12 14:05
Hey there @silveltman, we've actually solved for server-side HMR in our latest beta release (see link below). This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:05 UTC
