### ISSUE TITLE
Deployment with SST and open-next to AWS Lambda causes API routes to return 200 with no body

### ISSUE THREAD

**Issue by NicholasG04** [payloadcms/next-payload#74] opened 2023-09-22 22:48 UTC
Hi team,

We've been trying to deploy next-payload using SST and open-next on AWS. This appears to work at first, but then when you try to login, create a user etc. all of the API routes return 200 with no body. We don't see any errors in CloudWatch, and can't seem to see why this could be happening. We have confirmed that the exact same application deploys onto Vercel without any issues.

Thanks for any assistance you might be able to provide.

**Comment by lc-51** [comment] 2023-10-12 02:39
@NicholasG04, did you find a solution to this?  I'm experiencing the same issue at the moment.  Thanks.

**Comment by NicholasG04** [comment] 2023-10-12 05:53
No, sadly we had to switch to another CMS.

**Comment by david-mcbacon** [comment] 2023-11-27 21:22
Same issue here. Anyone with workaround or solution?

**Comment by jacobsfletch** [comment] 2024-04-12 14:14
Hey there @NicholasG04, @lc-51, and @david-mcbacon, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:14 UTC
