### ISSUE TITLE
App crashes with postgresql

### ISSUE THREAD

**Issue by Eric-Arz** [payloadcms/next-payload#106] opened 2024-01-17 09:42 UTC
The whole Next.js development server crashes (no error message, whole process just dies) when going to /admin

```
db: postgresAdapter({
        pool: {
            connectionString: 'postgres://postgres:postgres@localhost:5432/dbname',
        },
    }),
```

we are using:

```
"@payloadcms/db-postgres": "^0.3.1",
"@payloadcms/next-payload": "^0.1.11",
"@payloadcms/plugin-cloud-storage": "^1.1.1",
"@payloadcms/richtext-slate": "^1.3.1",
"next": "^13.5.6",
"payload": "^2.8.1",
```

problem occurs only on 2 out of 5 machines. All use same version of node.js and postgresql

**Comment by Eric-Arz** [comment] 2024-04-08 10:36
Seems like this is happening when payload can't connect to the database with that connection string for whatever reason (invalid password, etc.)

That being said this causing the whole Next.js app just crashing without any error message whatsoever is probably still an error.

**Comment by jacobsfletch** [comment] 2024-04-12 13:51
Hey @Eric-Arz, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 13:51 UTC
