### ISSUE TITLE
HMR doesn't work

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/next-payload#26] opened 2023-05-04 21:26 UTC
E.g. adding or changing a field. I have to reload the browser to see the change, which is extremely slow (>10s).

**Comment by jmikrut** [comment] 2023-06-26 21:33
Hey @johannesschaffer — this is on our roadmap to resolve within Payload directly, but the fix should also work for this NextJS package as well. 

Keep an eye out - this is coming shortly!

**Comment by ccapndave** [comment] 2023-09-11 11:48
I'm also experiencing this; is there any movement on it?

**Comment by jmikrut** [comment] 2023-09-23 03:14
Yes, we are aiming at solving this within Payload 2.0 which should directly solve the issue here as well. Keep an eye out for some news!

**Comment by jacobsfletch** [comment] 2024-04-12 14:19
Hey there @johannesschaffer, I left the same comment on @silveltman's ticket here: https://github.com/payloadcms/next-payload/issues/99, but we've actually solved for server-side HMR in our latest beta release (see link below).

This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the 3.x-beta label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 14:19 UTC
