### ISSUE TITLE
Warning: ToastContainer

### ISSUE THREAD

**Issue by 383bd03d** [payloadcms/next-payload#102] opened 2023-12-05 10:15 UTC
On a fresh project with deps:

```
{
    "@payloadcms/bundler-webpack": "^1.0.5",
    "@payloadcms/db-mongodb": "^1.1.0",
    "@payloadcms/next-payload": "^0.1.10",
    "@payloadcms/richtext-slate": "^1.2.1",
    "next": "14.0.3",
    "payload": "^2.3.1",
    "react": "^18",
    "react-dom": "^18"
  }
```

I get warn in terminal & browser:
`
Warning: ToastContainer: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
`

**Comment by 383bd03d** [comment] 2023-12-05 10:17
And also in a browser:
```
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: SideEffect(NullComponent)
```

**Comment by jacobsfletch** [comment] 2024-04-12 13:54
Hey @383bd03d, this repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/main/packages/next. Payload 3.0 ships with native support for Next.js and is currently out in beta here: https://github.com/payloadcms/payload-3.0-demo. I'm going to close this issue now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload). If think issue persists, feel free to open a new ticket on either the demo repo or the monorepo with the `3.x-beta` label, and be sure to include a reproduction so we can fix it faster.

**Closed by jacobsfletch** 2024-04-12 13:54 UTC
